### ISSUE TITLE
Ugly edges when mouse is near border

### ISSUE THREAD

**Issue by arturbien** [arturbien/3D-image#2]
One solution would be to add default styles to `canvas` and slightly zoom it in like so: 
```css
.image3D canvas {
    transform-origin: center;
    transform: scale(1.2);
}
````
this way the distorted image borders wouldt not be visible. Downside- not whole image will be visible
